### ISSUE TITLE
What happens?

### ISSUE THREAD

**Issue by evgen-kent** [cyntler/react-doc-viewer#10]
![image](https://user-images.githubusercontent.com/75276277/170465012-8531664a-eb06-470e-852c-670556c99dac.png)
![image](https://user-images.githubusercontent.com/75276277/170465357-7d13ed10-97d6-4373-80e9-8c0bc6f58938.png)

And also at the node modules I do not see ane index file with default  export :
![image](https://user-images.githubusercontent.com/75276277/170465100-0d745f6b-d309-465f-87a7-adad18350d76.png)

**Comment by the-usik** [comment]
You need to install **original** `react-doc-viewer` with `@cyntler/react-doc-viewer`. And import the react-doc-viewer in the your project.

**Comment by cyntler** [comment]
@evgen-kent @usein-abilev There was a bug in release.yml file (GitHub action) - right now, in the 1.0.4 package version all should be ok! ;) Sorry for that!
