### ISSUE TITLE
How to control the item that is displayed

### ISSUE THREAD

**Issue by lucasbbsdk** [cyntler/react-doc-viewer#109]
Hello,
I would like to be able to control on which document I am browsing based on a state variable. Is that possible?
So that each time a user navigate through the documents, it would reflect on the state variable

**Comment by cyntler** [comment]
@lucasbbsdk It is not possible at the moment. The Viewer uses local state management but it sounds like a good idea for a new feature: add props for `currentDocument` and `onDocumentChange` to get current document after switch.

**Comment by lucasbbsdk** [comment]
Okay, do you know if this is hard to do?
May I give that a try to open a pull request?

**Comment by cyntler** [comment]
@lucasbbsdk I work on this.

**Comment by cyntler** [comment]
@lucasbbsdk https://github.com/cyntler/react-doc-viewer#control-over-the-displayed-document
