### ISSUE TITLE
Error: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience.

### ISSUE THREAD

**Issue by anshOFS** [cyntler/react-doc-viewer#111]
### **Error Image:**

![error_message](https://user-images.githubusercontent.com/101546058/215810680-c89d0e59-2873-48ea-b935-442211e8adb8.png)

### **Error on screen:**

![issue_error](https://user-images.githubusercontent.com/101546058/215810761-b25834c2-8ab2-4353-847f-be96cdf61f0a.png)

### **Code used:**

![code_base](https://user-images.githubusercontent.com/101546058/215811534-9fa630b2-0076-443c-926a-5bebfc388c36.png)

**Comment by cyntler** [comment]
@anshOFS `createObjectURL` won't be working with MS Office files (docx too). Only public URL are supported.

**Comment by anshOFS** [comment]
> @anshOFS `createObjectURL` won't be working with MS Office files (docx too). Only public URL are supported.

Anything else that I can use in place of createObjectURL?

**Comment by cyntler** [comment]
@anshOFS Unfortunately not at the moment. MS Office documents are supported by public URL only. That's because the library uses MS Office Web Renderer provided by Microsoft and it works in the iframe.
