### ISSUE TITLE
Rendering Doc and Docx issues

### ISSUE THREAD

**Issue by jclinger** [cyntler/react-doc-viewer#12]
I'm trying to get a file to render that is already an ArrayBuffer data format, but most of the solutions always render from a file, or in this case from the "URI". 

I was looking into the Custom Renderer and Custom File Loader sections of the documentation to override how this is rendered or how the file is retrieved, but nothing seems to be working to get the ArrayBuffer data to display. 

Is there a way to use this library to to take a doc or docx ArrayBuffer and render it directly without a filename or URI?

**Comment by cyntler** [comment]
> I'm trying to get a file to render that is already an ArrayBuffer data format, but most of the solutions always render from a file, or in this case from the "URI".
> 
> I was looking into the Custom Renderer and Custom File Loader sections of the documentation to override how this is rendered or how the file is retrieved, but nothing seems to be working to get the ArrayBuffer data to display.
> 
> Is there a way to use this library to to take a doc or docx ArrayBuffer and render it directly without a filename or URI?

Thanks for your question! I will also try to do it in the next few days - I will let you know what I have done - I will also try to implement it in the library if I succeed.

**Comment by cyntler** [comment]
@jclinger OK, so currently it is not possible. The library is using "Office Web Viewer" (example: https://gist.github.com/theel0ja/b9e44a961f892ccf43e217ab74b9417b) and it requires a public url to the file.

**Comment by jclinger** [comment]
@cyntler  Okay, thanks for checking on that, I appreciate it.
