### ISSUE TITLE
How to set paginated: false for PDF rendering?

### ISSUE THREAD

**Issue by dangbert** [cyntler/react-doc-viewer#122]
I'd like to render a pdf with every page visible by vertical scrolling.  Scanning the codebase, I believe I can get this behaviour if I can set `paginated: false` in the PDFContext.  However I don't see a prop or config option to control the initial state for this.  I do see the function `setPDFPaginated()` in `src/renderers/pdf/state/actions.ts` but it's still unclear to me how I could call this when using the `<DocViewer />` component.

Any help/insights would be appreciated!

**Comment by cyntler** [comment]
@dangbert README: https://github.com/cyntler/react-doc-viewer/tree/main#config -> `pdfVerticalScrollByDefault`.
New v1.12.0 supports this.
