### ISSUE TITLE
Add ref to DocViewer

### ISSUE THREAD

**Issue by pitrudnicki** [cyntler/react-doc-viewer#127]
Greetings!
Is it possible to add references so that you can control the document yourself [e.g.: next/previous page, change zoom, etc...]?

I mean this code snippet
```
const docRef = useRef(null)
const nextPage = () => {
 if( docRef.current ) docRef.current.nextPage()
}
return (<>
<button onClick={nextPage}>next</button>
<DocViewer ref={docRef} />
</>)
```

**Comment by cyntler** [comment]
@pitrudnicki A good idea. It is not possible at the moment but sounds like a great idea to do. I marked it as a enhancement.

**Comment by cyntler** [comment]
@pitrudnicki Check it at the new version: https://github.com/cyntler/react-doc-viewer#using-docviewerref.

**Comment by RaflyLesmana3003** [comment]
it work but not for pdf pagination but for documents switching? its that true?

**Comment by cyntler** [comment]
@RaflyLesmana3003 Yes! It is true.
