### ISSUE TITLE
React doc viewer error occured with excel and doc file using blob url or local file

### ISSUE THREAD

**Issue by MohitRaykwar7389966852** [cyntler/react-doc-viewer#128]
I'm just trying to display different type of file in my react app so that's why I am using react doc viewer and I have given blob URL in docs , that's working for all the format but not working for excel and DOC file, any solution for this

**Comment by cyntler** [comment]
@MohitRaykwar7389966852 Duplicate: https://github.com/cyntler/react-doc-viewer/issues/61.
