### ISSUE TITLE
Remote URI PDF Problem

### ISSUE THREAD

**Issue by jkincho23** [cyntler/react-doc-viewer#132]
This is my URI.

let url = "http://localhost:8000/files/visualizeFile/" + idDoc;
errorpage.htm?llcc=es-ES&hid=73869138-aa13-4992-aa14-4f4c0bb66e35:1          
GET https://view.officeapps.live.com/op/es-ES/strings.js 404

**Comment by cyntler** [comment]
@jkincho23 Paste here more of your code, please. I don't understand.

**Comment by toanth-rk** [comment]
@cyntler My code here:
const docs = [
    {
      uri: `${process.env.NEXT_PUBLIC_API_ENDPOINT}/${document?.url}`,
    },
  ]
<DocViewer documents={docs} pluginRenderers={DocViewerRenderers} />.
It worked with "pdf" file but I have got same error like @jkincho23 when i used it for "docx" file .
I have received 404 Status: https://view.officeapps.live.com/op/vi-VN/strings.js
![image](https://user-images.githubusercontent.com/120642154/232362582-205061d2-c09d-4d86-9069-c8104c390fe4.png)

**Comment by jkincho23** [comment]
I have the same problem, my code looks like @toanth-rk, and i have the same error in the request about https://view.officeapps.live.com/op/vi-VN/strings.js, now i am using a iframe, so it just solve me a pdf file.

**Comment by cyntler** [comment]
@toanth-rk @jkincho23 try to change:
```js
{
  uri: `${process.env.NEXT_PUBLIC_API_ENDPOINT}/${document?.url}`
}
```

to:
```js
{
  uri: `${process.env.NEXT_PUBLIC_API_ENDPOINT}/${document?.url}`,
  fileType: 'application/pdf'
}
```
