### ISSUE TITLE
Unable to get pdf file from a http url

### ISSUE THREAD

**Issue by shruti2908** [cyntler/react-doc-viewer#133]
Hello, I am trying to use a https url which corresponds to a document file(pdf), and subsequently try to display it, but not able to do so, I am getting the following error:
<img width="637" alt="Capture" src="https://user-images.githubusercontent.com/23187236/232457893-be50d31d-fc2a-4a0a-8632-c36c573bf9a1.PNG">

**Comment by cyntler** [comment]
@shruti2908 I need more informations about your URL/data. Looks like the url is not available to fetch file by the browser.

**Comment by MobinurRahaman** [comment]
@shruti2908 I was facing the same issue. I got the following error in the console:

> Access to fetch at 'https://example1.com/file.pdf' from origin 'https://example2.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Open Developer tools by pressing F12 and check it under "Console" tab.

CORS errors are server sided and they are implemented for security. If you want to access that file, then you need to enable CORS on the server.

[This](https://github.com/FranckFreiburger/vue-pdf/issues/273) is a similar issue.

**Comment by SunnyArora175** [comment]
its not library issue, your browser is giving you cors error.  if you are using nextjs it can be fixed with a re-write rule which you can define in next.config.js

> @shruti2908 I need more informations about your URL/data. Looks like the url is not available to fetch file by the browser.

its not library issue, your browser is giving you cors error.  if you are using nextjs it can be fixed with a re-write rule which you can define in next.config.js

**Comment by SidWML** [comment]
@SunnyArora175  Iam using next js and  Iam getting url from the aws and when I use to render the file its stuck infinite loading
