### ISSUE TITLE
Locale ES - Fix for current page variable

### ISSUE THREAD

**Issue by jclipa** [cyntler/react-doc-viewer#141]
I created a PR with the change to fix the 'ES' locale current page -> https://github.com/cyntler/react-doc-viewer/pull/140

<img width="172" alt="image" src="https://github.com/cyntler/react-doc-viewer/assets/44736778/d6a94e11-f82f-42b1-b878-0bdbc55f9ff0">

**Comment by cyntler** [comment]
@jclipa Thanks! Merged!
