### ISSUE TITLE
Getting an error when committing to git 

### ISSUE THREAD

**Issue by Alimalik11** [cyntler/react-doc-viewer#144]
<img width="570" alt="Screenshot 2023-07-10 at 12 31 13 AM" src="https://github.com/cyntler/react-doc-viewer/assets/51762918/85d86024-0568-4421-983f-0cbb651a4d70">

Getting this error when committing to git?

**Comment by arora-sajan13** [comment]
@Alimalik11 I'm facing the same issue how did you happen to fix this ?

**Comment by Alimalik11** [comment]
I was not able to solve it.
________________________________
