### ISSUE TITLE
Unable to render document view

### ISSUE THREAD

**Issue by jakkub21** [cyntler/react-doc-viewer#15]
Hi, i would like to ask how to resolve this problem:
![obrázok](https://user-images.githubusercontent.com/53193386/175018311-1288923a-08be-4c6b-9655-45503c090eda.png)

As you can see my file from AWS S3 bucket is fetched but viewer doesn't render content and i don't understand why content type is set to multipart/form-data

Thanks for answer.

**Comment by jakkub21** [comment]
@cyntler Hi, yes i can. 
But i found some way to render this doc preview. So you can considered it as closed issue.

For those who will experience similar problem you can try this:

1. First use URL and parse it to get document type from it (my filename contain multiple dots so i used total length of array that was created from split function and get the last one):
```jsx
const splittedURI = uri.split('.')
const fileType = splittedURI[splittedURI.length - 1] || "pdf" // just to be safe i used PDF in case there is no match
```

2. Then you can specify document type in DocViewer component like this:
```jsx
<DocViewer 
      prefetchMethod="GET"
     pluginRenderers={DocViewerRenderers}
     documents={[ { uri: uri, fileType: fileType }]} 
/>
```

**Comment by cyntler** [comment]
@jakkub21 Nice! Thanks for your summary.
