### ISSUE TITLE
Doc and Docx files are not rendering on React application

### ISSUE THREAD

**Issue by karthik29a** [cyntler/react-doc-viewer#151]

**Comment by david-feldman** [comment]
Also having this issue 
![Screen Shot 2023-07-30 at 6 45 44 PM](https://github.com/cyntler/react-doc-viewer/assets/20193771/c3ab333a-19d3-44ca-b024-801dbc57a381)

**Comment by PiotrMocan** [comment]
it's because MS files renders through external application that can't load the file from localy or non-public servers

**Comment by david-feldman** [comment]
Thanks @PiotrMocan - I was able to solve this via using signed URLs from S3, setting CORs configs as mentioned in the tagged duplicate, and also by properly setting MIME metadata in the S3 upload. Now this functions fully w/ private files of all types.

**Comment by karthik29a** [comment]
Thanks @PiotrMocan  I am able to view files in my application after making URLs as public
