### ISSUE TITLE
Please integrate pdfjs

### ISSUE THREAD

**Issue by vnt-83** [cyntler/react-doc-viewer#157]
Each time a PDF document is opened, the `pdf.worker.min.js` file is downloaded. This file is already installed as a dependency on react-pdf: `node_modules/pdfjs-dist/legacy/build/pdf.worker.min.js`. The problem is that the end user may have closed external sites. It is also wrong to re-download 1.4 MB every time you open a document.

**Comment by cyntler** [comment]
@vnt-83 OK! I will check it.

**Comment by vnt-83** [comment]
https://github.com/cyntler/react-doc-viewer/issues/180#issuecomment-1742880167

**Comment by cyntler** [comment]
@vnt-83 Check the latest version. Should be ok now.

**Comment by vnt-83** [comment]
> @vnt-83 Check the latest version. Should be ok now.

No, pdf.worker.min.js continues to be downloaded from unpkg.com.

![pdf1](https://github.com/cyntler/react-doc-viewer/assets/16693651/bb22979e-32dc-45e8-a307-cf9cc6949069)
![pdf2](https://github.com/cyntler/react-doc-viewer/assets/16693651/762e606a-6608-4663-9742-2b686b88f1d7)
![pdf3](https://github.com/cyntler/react-doc-viewer/assets/16693651/b53f08ef-e3cd-4839-9bcc-de9e34810bf7)

**Comment by stephan-playbk** [comment]
Can confirm, on version v1.14.1
