### ISSUE TITLE
No option to disable download options  

### ISSUE THREAD

**Issue by ashishsah1000** [cyntler/react-doc-viewer#164]
I went through the docs but I did not find a way through which I can disable the download option for every type of file. Right now anyone has to look for the `CSS` class and add `display: none`. But it has to be done for every type of file.

 This `CSS` method does not work with Word and PowerPoint documents. So as of now, I have not found any workaround for these types of files.

**Comment by ashishsah1000** [comment]
I don't think that this lib has control over it...

```
 react_1.default.createElement(IFrame, { id: "msdoc-iframe", title: "msdoc-iframe", src: "https://view.officeapps.live.com/op/embed.aspx?src=".concat(encodeURIComponent(currentDocument.uri)), 
```

**Comment by cyntler** [comment]
@ashishsah1000 No. This lib hasn't control over it.
