### ISSUE TITLE
Support to render current document

### ISSUE THREAD

**Issue by YashD5291** [cyntler/react-doc-viewer#17]
Can we add support to render the current document by passing an index or something from the list of documents that we pass as props? 
or do we have configs for that in the current version?

**Comment by cyntler** [comment]
@YashD5291 Currently it is not supported. Good idea! If you want, you can try to add this feature to the project by Pull Request. Otherwise I can do it in the free time.

**Comment by cyntler** [comment]
@YashD5291 I implemented a new prop `initialActiveDocument` and released a new version 1.3.0 to support this feature. I tested and it looks like working fine but you can also try. How to implement? Check it here: https://github.com/cyntler/react-doc-viewer#initial-active-document. Of course remember to update version to 1.3.0.
