### ISSUE TITLE
Can't import individual renderers.

### ISSUE THREAD

**Issue by alan-cushla** [cyntler/react-doc-viewer#173]
Hi. I'm not able to import individual renders in the way the docs suggest. This doesn't work:
`import DocViewer, { PDFRenderer, PNGRenderer } from "@cyntler/react-doc-viewer";`
I think the issue is in the https://github.com/cyntler/react-doc-viewer/blob/main/src/renderers/index.ts file where you're importing all the renderers but only exporting them as part of the `DocViewerRenderers` array and not also as independent items.

**Comment by cyntler** [comment]
@alan-cushla Fixed.

**Comment by alan-cushla** [comment]
@cyntler , @maxikucan thanks for your help!
