### ISSUE TITLE
DocViewer does not have a construct or valid call signatures

### ISSUE THREAD

**Issue by JosuerBague** [cyntler/react-doc-viewer#175]
I am following the documentation and importing DocViewer like so:

```
import DocViewer, { DocViewerRenderers } from '@cyntler/react-doc-viewer'

const Component: React.FC = () => {
  return {
     <DocViewer/
          documents={[uri: <http>, fileType: 'pdf']}
          pluginRenderers={DocViewerRenderers}
     >
  }
}
```

I get the following error:
![image](https://github.com/cyntler/react-doc-viewer/assets/90120572/cfee9de5-ccdb-4ad7-b563-e4b620485b37)

When I try to do module augmentation, this error goes away:
![image](https://github.com/cyntler/react-doc-viewer/assets/90120572/4a588384-9020-4644-9647-7535af6efb38)

However this results in this error:
`Uncaught SyntaxError: ambiguous indirect export: DocumenViewe;

How can I solve this?

**Comment by SofianeBoumedine** [comment]
Same here, any solutions ?

**Comment by JosuerBague** [comment]
> Same here, any solutions ?

Hey, I got it to work using this:
`
import DocViewer, { DocViewerRenderers } from '@cyntler/react-doc-viewer';
import { type DocViewerProps } from '@cyntler/react-doc-viewer/dist/esm/DocViewer.js';

const DocumentViewer = DocViewer as unknown as React.FC<DocViewerProps>;

 // Some react code
            <Grid item className={styles.preview}>
                <DocumentViewer
                    className={styles.viewer}
                    documents={documents}
                    pluginRenderers={DocViewerRenderers}
                />
            </Grid>
`

Hope this helps.
