### ISSUE TITLE
Adding auth header

### ISSUE THREAD

**Issue by chrisa23** [cyntler/react-doc-viewer#18]
I need to add an authorization header to the file load.  Is there an easy way that I can do that?  I looked at the custom loader code and the internal fileLoader, but couldn't get anything I've tried so far to work.  I want to use the built in renderers.  Any help is appreciated.

**Comment by cyntler** [comment]
@chrisa23 Good idea! Looks like the important functionality. If you want, you can take care of it and prepare PR. If not, I will take care of it in the next days.

**Comment by chrisa23** [comment]
I'm probably not the best person to do a PR for a React library since I'm a C# dev that dabbles in React for a client project...  I will be incredibly grateful if the functionality is added though!

**Comment by cyntler** [comment]
@chrisa23 OK! Thanks!

**Comment by cyntler** [comment]
@chrisa23 Merged! Thanks for your work! Available in the new version: 1.4.0.

**Comment by chrisa23** [comment]
Awesome!  thanks!

**Comment by chrisa23** [comment]
Seems like prefetch works but then there is a second call to load the file that is missing the header.  Is the actual file loader skipping the headers?
`
const _fileLoader: BaseFileLoaderFunction = ({
  documentURI,
  signal,
  fileLoaderComplete,
  readerTypeFunction,
}) => {
  **return fetch(documentURI, { signal })**
    .then(async (res) => {
      const blob = await res.blob();
`

**Comment by cyntler** [comment]
> Seems like prefetch works but then there is a second call to load the file that is missing the header. Is the actual file loader skipping the headers?
> `const _fileLoader: BaseFileLoaderFunction = ({ documentURI, signal, fileLoaderComplete, readerTypeFunction, }) => { **return fetch(documentURI, { signal })** .then(async (res) => { const blob = await res.blob();`

Probably yes. I will check it.

**Comment by cyntler** [comment]
@chrisa23 Check again please! A new version has been released - 1.4.1.

**Comment by chrisa23** [comment]
Thanks for the fix. Works great now!
