### ISSUE TITLE
Style issue after upgrading to latest version

### ISSUE THREAD

**Issue by jcvegan** [cyntler/react-doc-viewer#184]
After upgrading to version 1.14.0 I noticed that assigning a custom background color is not being respected:

``<DocViewer
                prefetchMethod="GET"
                pluginRenderers={DocViewerRenderers}
                documents={attachments}
                initialActiveDocument={selectedAttachment}
                requestHeaders={{
                  Authorization: `bearer ${accessToken}`,
                }}
                theme={docTheme}
                style={{
                  backgroundColor: theme.palette.background.paper,
                }}
              />``

Sending the backgroundColor in the style prop is not working, background color is always set to white

**Comment by cyntler** [comment]
@jcvegan Thanks for the reporting. I will fix.

**Comment by cyntler** [comment]
@jcvegan 
v1.14.1 has been released! It should be fixed.
https://github.com/cyntler/react-doc-viewer/releases/tag/v1.14.1

**Comment by jcvegan** [comment]
Hi @cyntler thanks! it is working now
