### ISSUE TITLE
Unable to Copy Text from PDF in Production Environment

### ISSUE THREAD

**Issue by Manoj98Gopal** [cyntler/react-doc-viewer#188]
Issue Description:
In my project, I am utilizing the "@cyntler/react-doc-viewer" library for PDF rendering. However, I have encountered a specific issue related to the rendering and text copying functionality between my local development environment and the production environment.

Problem Description:

In the Local Environment, the PDF is rendered correctly, and I can copy the content of the PDF without any issues.

However, when the project is deployed to the Production Environment, the PDF is initially rendered as expected, but afterward, raw text is also being displayed. This, in turn, prevents me from copying the content of the PDF.

Expected Behavior:
I would expect the PDF to be consistently rendered in both the local and production environments, allowing for text selection and copying in both cases.

my code 

import DocViewer, { DocViewerRenderers } from "@cyntler/react-doc-viewer";

<DocViewer
        // className="viewer sc-hzhJZQ fxPyEs"
        documents={[{ uri: resume, fileType: "pdf" }]}
        key={viewerKey}
        pluginRenderers={DocViewerRenderers}
       
        config={{
          header: { disableHeader: true },
          loadingRenderer: {
            showLoadingTimeout: 3000,
          },
        }}
      />

**Comment by pat721** [comment]
This is probably a known issue (React-PDF version update) and a fix has been made with #185. It will be featured in an upcoming release. 

Until then, you can try to add the css imports for the text- and annotationlayer ([React-PDF: Import Text and Annotationlayer](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#support-for-annotations)) and see if this fixes your issue. Let us know if that helped.

**Comment by Manoj98Gopal** [comment]
Thank you for your response
could you please send a code example for the above solution, ( in react)

**Comment by pat721** [comment]
I would guess something like this. I just copied your code and added the lines.

```
import DocViewer, { DocViewerRenderers } from "@cyntler/react-doc-viewer";
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";

<DocViewer
// className="viewer sc-hzhJZQ fxPyEs"
documents={[{ uri: resume, fileType: "pdf" }]}
key={viewerKey}
pluginRenderers={DocViewerRenderers}

    config={{
      header: { disableHeader: true },
      loadingRenderer: {
        showLoadingTimeout: 3000,
      },
    }}
  />

```

**Comment by cyntler** [comment]
Try to use the latest version (1.16.2) and use it line in your projects: https://github.com/cyntler/react-doc-viewer?tab=readme-ov-file#required-styles
