### ISSUE TITLE
PDF rendering issue

### ISSUE THREAD

**Issue by NagasuryaJ** [cyntler/react-doc-viewer#191]
I want to display a PDF or Word document that is accessed via an S3 URL. However, when I attempted to retrieve the PDF document, I noticed that the content of each page was duplicated.
![Screenshot from 2023-10-23 20-00-48](https://github.com/cyntler/react-doc-viewer/assets/143582042/d1bd50b9-4d1a-467a-81cf-3da5170c0f11)

<DocViewer
                      documents={docs}
                      pluginRenderers={DocViewerRenderers}
                      className="custom-doc-viewer"
                      theme={{
                        primary: "rgb(243 244 246)",
                        secondary: "#ffffff",
                        tertiary: "#ffffff",
                        textPrimary: "#000000",
                        textSecondary: "#5296d8",
                        textTertiary: "#000000",
                        disableThemeScrollbar: true,
                      }}
                      config={{
                        header: { disableHeader: true },
                        pdfZoom: {
                          defaultZoom: 0.7,
                        },
                      }}
                    />
                    
                    
   **also the custom styling is also not supported here.**
   
   .custom-doc-viewer {
    height: 1000px !important;
  }
  
  @media (max-width: 768px) {
    .custom-doc-viewer {
      height: 500px !important;
    }
  } 
  
  "@cyntler/react-doc-viewer": "^1.14.0",
  "react": "^17.0.2",

**Comment by MuhammadDanishSiddiqui1988** [comment]
same issue facing

**Comment by pat721** [comment]
This is a known issue (React-PDF version update) and a fix has been made with #185. It will be featured in an upcoming release. 

Until then, you can try to add the css imports for the text- and annotationlayer ([React-PDF: Import Text and Annotationlayer](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#support-for-annotations)) and see if this fixes your issue. 

All you need to add is: 
`
import 'react-pdf/dist/Page/TextLayer.css';
import 'react-pdf/dist/Page/AnnotationLayer.css';
`

Let us know if that helped.

**Comment by cyntler** [comment]
v1.14.1 has been released! It should be fixed.
https://github.com/cyntler/react-doc-viewer/releases/tag/v1.14.1

**Comment by Kaliyani** [comment]
@cyntler I am using v1.14.1. Still I am facing the same issue. Can you help me to resolve this issue
