### ISSUE TITLE
AnnotationLayer.css Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by huy126123** [cyntler/react-doc-viewer#197]
i just import DocViewer, { DocViewerRenderers } from "@cyntler/react-doc-viewer";
And it have this error
./node_modules/react-pdf/dist/esm/Page/AnnotationLayer.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@cyntler\react-doc-viewer\dist\esm\renderers\pdf\index.js
I don't know how to fix :<

**Comment by durra-developer** [comment]
you can use "1.12.0"  version

**Comment by sarthsksingh077** [comment]
even after using version 1.12.0 in next js 13, its not working ?? please help @cyntler @durra-developer

**Comment by nnurmano** [comment]
Hi! Any updates on this topic?

**Comment by Olamide-Bello** [comment]
> you can use "1.12.0" version

Works for me

**Comment by sarthsksingh077** [comment]
![WhatsApp Image 2024-05-09 at 11 01 00](https://github.com/cyntler/react-doc-viewer/assets/64774472/949e375f-eeff-4961-88b5-37845cebec7e)

**Comment by cyntler** [comment]
Try to use the latest version (1.16.2) and use it line in your projects: https://github.com/cyntler/react-doc-viewer?tab=readme-ov-file#required-styles
