### ISSUE TITLE
Syntax Error react-pdf

### ISSUE THREAD

**Issue by WhiteBread1** [cyntler/react-doc-viewer#217]
Everything was working  fine, but I did a new install of node_modules and now I receive this error

<localpath>@cyntler/react-doc-viewer/node_modules/react-pdf/dist/esm/Page/AnnotationLayer.css:16
:root {
^

SyntaxError: Unexpected token ':'

**Comment by osanchezestoko** [comment]
I have the same error, I've tried different ways to solve it but continues failing

**Comment by milad7290** [comment]
Same here...

**Comment by syaifulamir** [comment]
same here

**Comment by alantoa** [comment]
I'm sure this PR will fix this issue. https://github.com/cyntler/react-doc-viewer/pull/235
If you guys want to make it work, just comment out the import CSS lines and patch it.

**Comment by cyntler** [comment]
Try to use the latest version (1.16.2) and use it line in your projects: https://github.com/cyntler/react-doc-viewer?tab=readme-ov-file#required-styles
