### ISSUE TITLE
Iam not able to load from aws urls

### ISSUE THREAD

**Issue by SidWML** [cyntler/react-doc-viewer#219]
https://static-sq-chat.s3.amazonaws.com/uploads/98820cea/D_Strange-Girl_Meets_Boy_Penguin_Readers-1-min.pdf?AWSAccessKeyId=adghakdehaoyKLKHSnKLhljKLDHklabdx&Signature=fsdfDsfsfsfsfsfD&Expires=1704870237
<DocViewer documents={[{uri:'/movies100.pdf'}]} pluginRenderers={DocViewerRenderers} prefetchMethod="GET" />
Iam not able to load from the above path but files from local are working fine

**Comment by roy-andri** [comment]
Have you set up the cors on your AWS  bucket?

https://repost.aws/knowledge-center/s3-configure-cors
```
[
    {
        "AllowedHeaders": [
            "Authorization"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*" <-- Put your whitelist URL here
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin"
        ]
    }
]
```

**Comment by SidWML** [comment]
@roy-andri Thanks but I have a question if paste the urls in the browser Iam able to download the pdfs but in the app it got stuck in a infinte loop loader 
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/b36bfa1c-e1b2-40ee-b596-738bf509ea67)

**Comment by roy-andri** [comment]
> Thanks but I have a question if I paste the urls in the browser Iam able to download the pdfs but in the app it got stuck in a infinte loop loader

For this one, have you put the `fileType`? Can you share your network tab while requesting the document from AWS? Is it getting 200?

**Comment by SidWML** [comment]
@roy-andri  Here it is
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/eb98c628-f9b9-453f-9cc3-0895241bf680)

**Comment by roy-andri** [comment]
I guess there is something wrong with your CORS configuration, I will facing the same issue if I remove the CORS configuration from my AWS bucket.

**Comment by SidWML** [comment]
@roy-andri  Thank you very much

**Comment by SidWML** [comment]
Hi @roy-andri thanks for the solution above its working for pdf but its not working for doc and docx 
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/069f479c-6f93-4142-add8-6e61b5f7b419)

**Comment by roy-andri** [comment]
How do you handle the rendering process? Can you share your code, maybe there is something wring with your rendering.

https://support.mozilla.org/en-US/kb/xframe-neterror-page

**Comment by SidWML** [comment]
Hi @roy-andri  thanks for the reply i appreciate this is the code 
const docs = [{uri:docURL ,fileType:'doc'}]  
<DocViewer
                                      className='w-[60%]'
                                                    prefetchMethod="GET"
                                                        documents={docs}
                                                        pluginRenderers={
                                                            DocViewerRenderers
                                                        }
                                                    />

**Comment by roy-andri** [comment]
Are you facing this error on the local or after you deploy the website? can you make sure the file type is doc, not docx?

Here is how I call this library, with this code, I can preview 3 different file types (doc/x,pdf,txt)
```
      <DocViewer
        documents={[
          {
            uri: url,
            fileType: extension,
          },
        ]}
        config={{
          header: { disableHeader: true },
          pdfVerticalScrollByDefault: true,
        }}
        prefetchMethod="GET"
      />
```

**Comment by SidWML** [comment]
@roy-andri  and this is what I am getting when I open it in mirrosoft edge 
![Uploading image.png…]()

**Comment by SidWML** [comment]
@roy-andri its in local what is this extension the file I have to display 3 types pdf,doc and docx

**Comment by roy-andri** [comment]
> what is this extension the file I have to display 3 types pdf,doc and docx
It's depends on your file, if your file is `docx` then the `fileType` should `docx` as well

**Comment by SidWML** [comment]
@roy-andri 
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/092db5cd-e94e-4912-976d-96c60db30eb0)
this is what in the network headers

**Comment by SidWML** [comment]
@roy-andri 
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/c188435b-cfc2-4551-9935-0f1e719756a5)

**Comment by roy-andri** [comment]
Have you tried using incognito tab?

**Comment by roy-andri** [comment]
"@cyntler/react-doc-viewer": "^1.14.1"

**Comment by SidWML** [comment]
@roy-andri Iam using the same package thanks for the help

**Comment by roy-andri** [comment]
It seems your file URL is empty @SidWML 

<img width="853" alt="Screenshot 2024-01-12 at 10 43 31 PM" src="https://github.com/cyntler/react-doc-viewer/assets/120375328/663de126-bd47-4a78-8069-841d45be8a41">

I also facing same issue if I try set the file URL using empty string.

<img width="463" alt="Screenshot 2024-01-12 at 10 43 03 PM" src="https://github.com/cyntler/react-doc-viewer/assets/120375328/a25b8e09-f77c-4f71-b3f8-70bb5593b2df">
<img width="1439" alt="Screenshot 2024-01-12 at 10 42 34 PM" src="https://github.com/cyntler/react-doc-viewer/assets/120375328/811a2487-d34b-48e1-8c79-d263ddfc70d7">

**Comment by roy-andri** [comment]
It should contain your file URL
<img width="940" alt="Screenshot 2024-01-12 at 10 46 49 PM" src="https://github.com/cyntler/react-doc-viewer/assets/120375328/60b06702-1445-474d-95d3-2259033a317d">

**Comment by SidWML** [comment]
@roy-andri  thanks man I have wrote a condition where Iam storing the docURL I missed to check .Thank you once again Its working
