### ISSUE TITLE
Doc / Docx files from both local and urls are not working

### ISSUE THREAD

**Issue by SidWML** [cyntler/react-doc-viewer#220]
<DocViewer documents={[{uri:'/dum.doc', fileType: "doc",}]} pluginRenderers={DocViewerRenderers} /> but local doc files are not getting show there is an error 
![doc](https://github.com/cyntler/react-doc-viewer/assets/115688990/6f67d48c-e015-47be-b2cf-26ba6cc1ff74)

**Comment by abdnafees** [comment]
Same here. I think the default Request URL points to [view](https://view.officeapps.live.com/) which requires authentication.

**Comment by SidWML** [comment]
@abdnafees did you find any solution for this

**Comment by SidWML** [comment]
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/d8731645-ead7-479a-a08f-7c35a7b1acda)
@cyntler  I am getting this error when I try to render doc and docs files

**Comment by sridharvemulapalli** [comment]
If you are using the local file, please change the doc object uri to use require.

ex : { uri: require('<path of your pdf>'), fileType: 'pdf' }
