### ISSUE TITLE
 continous loading

### ISSUE THREAD

**Issue by SidWML** [cyntler/react-doc-viewer#221]
I am rendering files from aws s3 bucket but Iam able to see a continous loading 
![image](https://github.com/cyntler/react-doc-viewer/assets/115688990/64c8cf0b-d0cd-4600-aa63-ce1924239b6b)

**Comment by SidWML** [comment]
it was CORS need to set CORS

**Comment by shehjad-dev** [comment]
Bro, where you set cors on aws??
