### ISSUE TITLE
Canvas error in Next.js

### ISSUE THREAD

**Issue by raviprakash1408** [cyntler/react-doc-viewer#224]
Getting this error when I am trying to render any type of document. How to fix it?

./node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by mohitmaliLL** [comment]
@raviprakash1408, Did you get any solution for this??

**Comment by snylonue** [comment]
Same issue

**Comment by emystein** [comment]
Using https://github.com/eisberg-labs/nextjs-node-loader/ worked for me.

**Comment by raflimaulanayh** [comment]
> Using https://github.com/eisberg-labs/nextjs-node-loader/ worked for me.

wow thank you bro this works on me too
