### ISSUE TITLE
File storage and security

### ISSUE THREAD

**Issue by ron4eg1992** [cyntler/react-doc-viewer#233]
Hello! Tell me how the library works, where are my files sent or stored? Is there some kind of protection to prevent files from becoming publicly available??

**Comment by cyntler** [comment]
@ron4eg1992 This is a frontend library and all of your files you want to display on a page have to be stored on the backend side or something like that. The library loads the files in fly when component is rendering. You should to use public URLs to the files. If the browser has an access to file - the library also has. Everything about security is on your side. If a file isn't publicly available, you probably don't want to display it publicly. And if you really want to, you need to somehow authenticate the client/user to process such a file.
