### ISSUE TITLE
Hide bottom toolbar or disable download option in react-doc-viewer

### ISSUE THREAD

**Issue by salaimuniselvam-s** [cyntler/react-doc-viewer#253]
I  have integrated React-Doc-Viewer into my application to display DOCX files. I need to restrict users from downloading these files, but the React-Doc-Viewer includes a bottom toolbar that allows downloading. It doesn't seem to be a built-in prop to hide or disable this toolbar.

looking for a solution to either hide the bottom toolbar or restrict the download option for users.

I attempted to use CSS to hide the bottom toolbar, but since the document is displayed within an iframe, the CSS didn't have the desired effect.

https://stackoverflow.com/questions/78481650/hide-bottom-toolbar-or-disable-download-option-in-react-doc-viewer

**Comment by cyntler** [comment]
> I have integrated React-Doc-Viewer into my application to display DOCX files. I need to restrict users from downloading these files, but the React-Doc-Viewer includes a bottom toolbar that allows downloading. It doesn't seem to be a built-in prop to hide or disable this toolbar.
> 
> looking for a solution to either hide the bottom toolbar or restrict the download option for users.
> 
> I attempted to use CSS to hide the bottom toolbar, but since the document is displayed within an iframe, the CSS didn't have the desired effect.
> 
> https://stackoverflow.com/questions/78481650/hide-bottom-toolbar-or-disable-download-option-in-react-doc-viewer

Could you please attach a screenshot of this?

**Comment by Aliouzidouh** [comment]
> > I have integrated React-Doc-Viewer into my application to display DOCX files. I need to restrict users from downloading these files, but the React-Doc-Viewer includes a bottom toolbar that allows downloading. It doesn't seem to be a built-in prop to hide or disable this toolbar.
> > looking for a solution to either hide the bottom toolbar or restrict the download option for users.
> > I attempted to use CSS to hide the bottom toolbar, but since the document is displayed within an iframe, the CSS didn't have the desired effect.
> > https://stackoverflow.com/questions/78481650/hide-bottom-toolbar-or-disable-download-option-in-react-doc-viewer
> 
> Could you please attach a screenshot of this?

Hello @cyntler i also have the same issue when trying  to hide the bottom toolbar, like @salaimuniselvam-s said the css have no effect because the document is displayed within an iframe
<img width="1792" alt="Screenshot 2024-05-24 at 09 25 06" src="https://github.com/cyntler/react-doc-viewer/assets/130761430/a4300ca6-5d33-4626-8f69-9be83edd84ed">

PS: when applying  the style directly in the console it works
<img width="1789" alt="image" src="https://github.com/cyntler/react-doc-viewer/assets/130761430/4ab9f958-93bf-4686-b1a3-beda9109b31a">

**Comment by cyntler** [comment]
@Aliouzidouh OK but MS Office renderer is working as an embedded **IFRAME** element with official MS service. There are not native possibility to render MS Office files in the browser. It means, there are not possibility to override CSS styles of the iframe. So sorry.
