### ISSUE TITLE
External Microsoft service usage

### ISSUE THREAD

**Issue by shura-v** [cyntler/react-doc-viewer#255]
The documentation does not mention the fact that this library makes full use of an external Microsoft service, which may be unacceptable for many projects.

**Comment by cyntler** [comment]
@shura-v Yes, that's right! It should be mentioned at the readme file.

Recently, I have an idea to build a completely new version of this library along with a backend version in the cloud, where files such as MS Office files will be converted to PDF/image on the fly and displayed custom in the browser. But such a backend will definitely not be open source and access to it will be paid.

**Comment by cyntler** [comment]
@shura-v I have been added this info at the readme file.
