### ISSUE TITLE
Bypass password for protected files

### ISSUE THREAD

**Issue by kamelabiad** [cyntler/react-doc-viewer#257]
Hi,

I was wondering if there is a way to bypass the password for protected files, avoiding the popup that asks the user to enter their password. I checked the code and didn't find anything related to the popup message: "Enter the password to open this PDF file."

**Comment by kamelabiad** [comment]
@cyntler Thanks for getting back to me. Are you providing the full source code for this tool? I would like to look into it because I wasn't able to find the message "Enter the password to open this PDF file" when I checked the GitHub repo.

**Comment by cyntler** [comment]
@kamelabiad To render PDF files, the library uses: https://github.com/wojtekmaj/react-pdf. I see, there are prop/props regarding to password topic but it is not handled in our library.

**Comment by kamelabiad** [comment]
Thanks i managed to handle that
