### ISSUE TITLE
Can we please upgrade to latest react-pdf version

### ISSUE THREAD

**Issue by xiaolongkipsi** [cyntler/react-doc-viewer#262]
9.0.0 has the security fix
https://github.com/wojtekmaj/react-pdf/releases

**Comment by stefan1968** [comment]
Also, there is a breaking change as the code includes pdf-worker.min.js instead of the breaking change pdf-worker-min.mjs

As the dependency is react-pdf@latest it automatically installs version 9.0.0 as a dependency and doesn't work.

**Comment by cyntler** [comment]
v1.16.0 is experimental version with a lot of changes - especially about 9.0.0 of react-pdf upgrade. If you can, you can check if it is fine.

**Comment by xiaolongkipsi** [comment]
@cyntler I tried, I am using it in nextjs. but hitting below error:

```Error: Cannot find module '/Users/xiaolongjiang/Documents/workspace/tax/node_modules/@cyntler/react-doc-viewer/dist/esm/DocViewer' imported from /Users/xiaolongjiang/Documents/workspace/tax/node_modules/@cyntler/react-doc-viewer/dist/esm/index.js```

**Comment by xiaolongkipsi** [comment]
It's also failing when doing yarn build

  Collecting page data  ...Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/xiaolongjiang/Documents/workspace/tax/node_modules/@cyntler/react-doc-viewer/dist/esm/DocViewer' imported from /Users/xiaolongjiang/Documents/workspace/tax/node_modules/@cyntler/react-doc-viewer/dist/esm/index.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/xiaolongjiang/Documents/workspace/tax/node_modules/@cyntler/react-doc-viewer/dist/esm/DocViewer'
}

**Comment by cyntler** [comment]
@xiaolongkipsi Hmm, I tried to run it locally with Next.js and it is working.

**Comment by cyntler** [comment]
@xiaolongkipsi Check the example: https://github.com/cyntler/react-doc-viewer/tree/main/use-cases/nextjs

**Comment by xiaolongkipsi** [comment]
Can you try import with npm way? It seems you imported through your local
esm.


--

Xiaolong Jiang

Co-Founder & CTO, Kipsi

***@***.*** | LinkedIn
<https://www.linkedin.com/in/xiaolong-jiang-25b34441/>

**Comment by cyntler** [comment]
@xiaolongkipsi Yes. I can. Check it: https://github.com/cyntler/react-doc-viewer/blob/main/use-cases/nextjs/src/app/page.tsx. I installed officially deployed version of this library and it is still working fine as expected.

**Comment by xiaolongkipsi** [comment]
Everything seems it should work. I am using latest nextjs but with older
pages style. But it should not matter. I am still hitting the same error

--

Xiaolong Jiang

Co-Founder & CTO, Kipsi

***@***.*** | LinkedIn
<https://www.linkedin.com/in/xiaolong-jiang-25b34441/>

**Comment by cyntler** [comment]
@xiaolongkipsi Can you provide me more informations about your environment?
I mean:
- Node.js & npm versions
- Your package manager (npm/yarn/pnpm)?
- Next.js version

**Comment by xiaolongkipsi** [comment]
node: v20.12.2
npm: 10.5.0
I am using yarn
Nextjs version: 14.2.3

I tried your nextjs use case example, that is working for me though.

--

Xiaolong Jiang

Co-Founder & CTO, Kipsi

***@***.*** | LinkedIn
<https://www.linkedin.com/in/xiaolong-jiang-25b34441/>

**Comment by jcvegan** [comment]
I am getting same error:
node: v20.11.1
npm: 10.8.1

**Comment by cyntler** [comment]
@jcvegan @emikira @xiaolongkipsi Please check the latest version: 1.16.2. I migrated to Vite build/compilation system instead of pure TS..

**Comment by mxylin** [comment]
I got the same [ERR_MODULE_NOT_FOUND] error in v1.16.1
1.16.2 fixes the error for my project , thank you very much @cyntler
