### ISSUE TITLE
I encountered an installation issue when I attempted to install the package.

### ISSUE THREAD

**Issue by mehranjillani786** [cyntler/react-doc-viewer#267]
ERROR in ./src/components/DocumentViewer/index.js 14:21-39
export 'DocViewerRenderers' (imported as 'DocViewerRenderers') was not found in '@cyntler/react-doc-viewer' (possible exports: default)

ERROR in ./node_modules/@cyntler/react-doc-viewer/dist/esm/index.js 1:0-36
Module not found: Error: Can't resolve './DocViewer' in 'D:\learning\test\node_modules\@cyntler\react-doc-viewer\dist\esm'
Did you mean 'DocViewer.js'?
BREAKING CHANGE: The request './DocViewer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@cyntler/react-doc-viewer/dist/esm/index.js 3:0-49
Module not found: Error: Can't resolve './renderers' in 'D:\learning\test\node_modules\@cyntler\react-doc-viewer\dist\esm'
Did you mean 'index.js'?
BREAKING CHANGE: The request './renderers' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@cyntler/react-doc-viewer/dist/esm/index.js 4:0-25
Module not found: Error: Can't resolve './models' in 'D:\learning\test\node_modules\@cyntler\react-doc-viewer\dist\esm'
Did you mean 'models.js'?
BREAKING CHANGE: The request './models' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@cyntler/react-doc-viewer/dist/esm/index.js 5:0-36
Module not found: Error: Can't resolve './utils/fileLoaders' in 'D:\learning\test\node_modules\@cyntler\react-doc-viewer\dist\esm'
Did you mean 'fileLoaders.js'?
BREAKING CHANGE: The request './utils/fileLoaders' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 5 errors and 1 warning

**Comment by fedenelli** [comment]
+1

**Comment by smorton-planview** [comment]
See https://github.com/cyntler/react-doc-viewer/issues/268#issuecomment-2152271219

**Comment by cyntler** [comment]
@Mohon45 @fedenelli @mehranjillani786  Please check the latest version: 1.16.2. I migrated to Vite build/compilation system instead of pure TS.
