### ISSUE TITLE
When i try to build my react application then throw and error . (Module not found: Error: Can't resolve './DocViewer')

### ISSUE THREAD

**Issue by Mohon45** [cyntler/react-doc-viewer#268]
![Screenshot 2024-06-06 063033](https://github.com/cyntler/react-doc-viewer/assets/85331700/68d8a356-d938-4b70-aae9-6ceb50df5d68)

**Comment by Mohon45** [comment]
how to solve it?

**Comment by smorton-planview** [comment]
I am seeing the exact same issue with version 1.16.x and up. Prior versions didn't have this problem from what I can tell. The only way I got around this was to add the following into my webpack rules:

```javascript
{
  test: /\.m?js/,
  resolve: {
    fullySpecified: false,
  }
}
```

I am not a webpack expert so I don't really know if this config is problematic or not. I am curious why this was not required in prior versions of the component.

**Comment by Mohon45** [comment]
@smorton-planview  where i can write in this rules? i mean which file

**Comment by smorton-planview** [comment]
That depends on where you store your webpack config.

**Comment by cyntler** [comment]
OMG. Generic modules and module types in JS are probably one of the worst things to develop. Eternal problems. Each framework handles this differently...

**Comment by cyntler** [comment]
This problem probably is related to Webpack... https://webpack.js.org/configuration/module/#resolvefullyspecified. I don't know currently how I should to fix it on the library level.

**Comment by cyntler** [comment]
@Mohon45 @smorton-planview  Please check the latest version: 1.16.2. I migrated to Vite build/compilation system instead of pure TS.

**Comment by smorton-planview** [comment]
@cyntler I no longer see the build issues after upgrading to 1.16.2.  Thanks!

**Comment by cyntler** [comment]
> @cyntler I no longer see the build issues after upgrading to 1.16.2. Thanks!

Sounds great! Thanks for feedback!
