### ISSUE TITLE
Not able use the package in react 

### ISSUE THREAD

**Issue by itsCheithanya** [cyntler/react-doc-viewer#276]
when running ```npm start``` the compiler throws this error
![image](https://github.com/cyntler/react-doc-viewer/assets/85927700/1d4598d1-7470-48c4-931b-0680a8c6b665)

**Comment by cyntler** [comment]
@itsCheithanya More informations I need to can help. What kind of files are you trying to render? Paste here some of your code.

**Comment by itsCheithanya** [comment]
I was using node version 14 maybe that's why it didn't work , I updated the node to version 20 its working now and one more thing the code doesn't preview local docx and pptx files 
![image](https://github.com/cyntler/react-doc-viewer/assets/85927700/c47ae3d9-0178-4003-9c5f-261c8cefda7b)

```
import DocViewer, { DocViewerRenderers } from "react-doc-viewer";
import "@cyntler/react-doc-viewer/dist/index.css";

function App() {
  const docs = [
    { uri: require("./POSTER-2024_NO-FUND_Final.docx") },
  ];

  return <DocViewer documents={docs} pluginRenderers={DocViewerRenderers} />;
}
export default App;


```

**Comment by cyntler** [comment]
@itsCheithanya OK, so now your problem is what is described here: https://github.com/cyntler/react-doc-viewer?tab=readme-ov-file#important-note. So sorry but your **local** docx and pptx files can't be rendered. They must be public with access URL.
