### ISSUE TITLE
PDF Renderer not working

### ISSUE THREAD

**Issue by ruchirV** [cyntler/react-doc-viewer#280]
I am getting an error when I try to load PDF file. It was working fine before your last upgrade. I see the code modified and I see that the pdf-dist module is removed from the package.json, but the workerSrc is added from the same module: https://github.com/Alcumus/react-doc-viewer/commit/30c429c7b415ef352d3abb83576f30534cd88970. 

A screenshot of the error is attached. 

<img width="1335" alt="PDF-Renderer Error" src="https://github.com/cyntler/react-doc-viewer/assets/2942235/b0299094-8ac7-42f2-8394-1837eb0b8b76">

**Comment by cyntler** [comment]
@ruchirV This GitHub repo is related to `@cyntler/react-doc-viewer`. Your issue concerns another repo - original that I forked from. Are you sure you you are using @cyntler/react-doc-viewer? Your error on the screenshot tells about `react-doc-viewer`.
