### ISSUE TITLE
pdf page content is getting displayed twice in the same page

### ISSUE THREAD

**Issue by narinderCanGit** [cyntler/react-doc-viewer#289]
const docs = [
    {
      uri      : data,
      fileName : fileName
    }
  ];
  
<DocViewer pluginRenderers={DocViewerRenderers}
                  documents={docs}
                  config={{
                    header : {
                      disableHeader   : false,
                      disableFileName : true,
                      retainURLParams : false
                    },
                    pdfVerticalScrollByDefault : true,
                    disableExtractedTextAfterPage : true
                  }}
                />

In the attached image the highlighted text is the duplicate text. If I open the data blob url in the new tab, the pdf is rendered fine with no duplicate issue.
<img width="500" alt="image" src="https://github.com/user-attachments/assets/3980b2fb-aa8b-48de-9943-1b547ae67f5c">

**Comment by smorton-planview** [comment]
See https://github.com/cyntler/react-doc-viewer/issues/261. 

Adding the following import should sort you out:
```
import '@cyntler/react-doc-viewer/dist/index.css';
```
