### ISSUE TITLE
Re-render causes document to disappear

### ISSUE THREAD

**Issue by griffenr** [cyntler/react-doc-viewer#30]
Check PR for detailed information -> https://github.com/cyntler/react-doc-viewer/pull/29

**Comment by cyntler** [comment]
@griffenr Thanks so much! Merged! ;)

**Comment by cyntler** [comment]
@griffenr I revert your `dispatch(updateDocumentNumber());` in 1.4.5.
It is not working for me.

I see invalid current file no and my next/back arrows don't work.

**Comment by griffenr** [comment]
Can you provided steps to re-create this issue? I did some testing of my own by reworking the demo component and didn't notice any issues. I would like to try and get this resolved :)

**Comment by cyntler** [comment]
@griffenr I use Safari browser so I checked there. I have to check in Chrome additionally.

All what I did:
- I added next file to the `documents` array in `demo.tsx`
- I started `demo` app by `npm start`

When I switched the document with arrows, the wrong number of the current document was quickly shown (usually 0).

**Comment by griffenr** [comment]
@cyntler I am unable to test this in Safari so if you could confirm in Chrome that would be great. I cloned the 1.4.4 tag just to make sure I had the exact same code you did and am still not getting any errors and everything appears to be working fine.

**Comment by cyntler** [comment]
@griffenr Yes! In Chrome it is working fine.

**Comment by cyntler** [comment]
@griffenr I don't think we need those two dispatches:

```ts
        dispatch(updateDocumentNumber());
        dispatch(
          updateCurrentDocument({
            ...currentDocument,
            fileType: contentType || undefined,
          })
        );
```

Can't we merge this into one dispatch as it was before? `updateCurrentDocument` is updating `state.currentFileNo`. I don't understand we need this second dispatch.

Can you explain?

**Comment by griffenr** [comment]
@cyntler When a re-render is triggered, it will default the document to the one specified in the initialActiveDocument prop. Without this updateDocumentNumber dispatch, it will not sync the current page number to the correct page. I highly recommend setting up the demo.tsx file to contain a button that will trigger a re-render of the page so you can see this in action. Below I have pasted the code for the demo.tsx file that I'm using to test.

import React from "react";
import { createRoot } from "react-dom/client";
import DocViewer from ".";
import { DocViewerRenderers } from "./plugins";

const App = () => {

  const [ test, setTest ] = React.useState<boolean>( false );

  const docs = [
    { uri: require("./examples/pdf-file.pdf") },
    { uri: require("./examples/png-image.png") },
  ];

  return (
      <div style={ { background: test ? "blue" : "green" } }>
        <button onClick={ () => setTest( !test ) }>Re-render</button>
        <DocViewer
            documents={docs}
            initialActiveDocument={docs[1]}
            pluginRenderers={DocViewerRenderers}
            config={{
              noRenderer: {
                overrideComponent: ({ document, fileName }) => {
                  const fileText = fileName || document?.fileType || "";
                  if (fileText) {
                    return <div>no renderer for {fileText}</div>;
                  }
                  return <div>no renderer</div>;
                },
              },
              loadingRenderer: {
                overrideComponent: ({ document, fileName }) => {
                  const fileText = fileName || document?.fileType || "";
                  if (fileText) {
                    return <div>loading ({fileText})</div>;
                  }
                  return <div>loading</div>;
                },
              },
            }}
        />
      </div>
  );
};

const rootElement = document.getElementById("root");
if (rootElement) {
  const root = createRoot(rootElement);
  root.render(<App />);
}

**Comment by cyntler** [comment]
@griffenr OK! Now I understand this problem. I am looking for a solution.

**Comment by cyntler** [comment]
@griffenr OK, it looks like it has been fixed at PR: https://github.com/cyntler/react-doc-viewer/pull/35.
Check it in v1.5.1. I am interested if it will be working for you.

As you can see at the PR - a solution for this issue was changing `case SET_ALL_DOCUMENTS: {` case in the reducer.
