### ISSUE TITLE
can not preview local pdf file

### ISSUE THREAD

**Issue by fkbeys** [cyntler/react-doc-viewer#40]
i want to preview a local pdf file. but it shows this error.

Module not found: Error: You attempted to import C:\Users\Kaya\Desktop\kaya.pdf which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

 thank you

**Comment by robertodraGit** [comment]
you have to put the file inside your project directory

**Comment by fkbeys** [comment]
> you have to put the file inside your project directory

so, i should copy the file to the inside the project, then i will show?

**Comment by robertodraGit** [comment]
> > you have to put the file inside your project directory
> 
> so, i should copy the file to the inside the project, then i will show?

yup

**Comment by cyntler** [comment]
@fkbeys is it working?
