### ISSUE TITLE
Use blob content

### ISSUE THREAD

**Issue by osunaintarcon** [cyntler/react-doc-viewer#52]
Hi, I'm trying to implement the component on my platform but I get the documents (pdf, docx, xlsx,...) from the server as a blob object. I am having many problems to be able to visualize the documents.
Is there a way to deal with blob objects in this component? Thanks.

![image](https://user-images.githubusercontent.com/86778348/189317441-f71b49b6-2848-4a10-a454-d8508bacf881.png)

**Comment by robertodraGit** [comment]
Instead of passing the blob url, pass the API url to the component and make him do the fetch. Let me know

**Comment by osunaintarcon** [comment]
> Instead of passing the blob url, pass the API url to the component and make him do the fetch. Let me know

I have contemplated this form but when making the API call I need to pass some headers because I have a session token which I use so that only users who are on the platform can query the backend.

**Comment by robertodraGit** [comment]
> > Instead of passing the blob url, pass the API url to the component and make him do the fetch. Let me know
> 
> I have contemplated this form but when making the API call I need to pass some headers because I have a session token which I use so that only users who are on the platform can query the backend.

You can do it.

```
const headers = useMemo(() => ({
    "Authorization": `Bearer ${accessToken}`,
  }), [accessToken]);
```

Save the accessToken in the context and pass the header in the jsx like that
`<DocViewer requestHeaders={headers} ... />`

**Comment by osunaintarcon** [comment]
> > > Instead of passing the blob url, pass the API url to the component and make him do the fetch. Let me know
> > 
> > 
> > I have contemplated this form but when making the API call I need to pass some headers because I have a session token which I use so that only users who are on the platform can query the backend.
> 
> You can do it.
> 
> ```
> const headers = useMemo(() => ({
>     "Authorization": `Bearer ${accessToken}`,
>   }), [accessToken]);
> ```
> 
> Save the accessToken in the context and pass the header in the jsx like that `<DocViewer requestHeaders={headers} ... />`

Perfect it has worked for me.
Now I have another problem, the PDF is displayed perfectly but the .docx and .xlxs documents show me an error.
When I click on more information it shows me this.

![image](https://user-images.githubusercontent.com/86778348/189335620-0a4fcdf6-ccb2-4229-9651-a86197a7b5e8.png)
Can't find this web address https://www.office.com/redir.aspx?assetid=HA102724036.

**Comment by robertodraGit** [comment]
The problem here is that the docx and xlsx are trying to use the office live preview server, but your file isn't public so the office server can't access to it.
This problem can't be resolved actually

**Comment by osunaintarcon** [comment]
Ok, so I'll have to look for another alternative to be able to view .docx and .xlsx files.
Many thanks.

**Comment by cyntler** [comment]
In the future we probably need to switch to a different display method .doc and .xls.
