### ISSUE TITLE
Not able to preview local file selected through input tag.

### ISSUE THREAD

**Issue by shubhambatra** [cyntler/react-doc-viewer#53]
I am facing problem to show local files which user has selected throgh the input 
`let file = ''`;
 ` <input type="file" accept=".pdf" id="" multiple onChange={(el) => file = el.target.files }/>`
` <DocViewer
            pluginRenderers={DocViewerRenderers}
            config={{
              header: {
                retainURLParams: false
              }
            }}
            documents={[{
              uri: file ? file[0] : ''
            }]}`

**Comment by cyntler** [comment]
@shubhambatra Please update your `@cyntler/react-doc-viewer` to v1.6.2. Then below code should be working:

```jsx
const DocViewerWithInputApp = () => {
  const [selectedDocs, setSelectedDocs] = useState<File[]>([]);

  return (
    <>
      <input
        type="file"
        accept=".pdf"
        multiple
        onChange={(el) =>
          el.target.files?.length &&
          setSelectedDocs(Array.from(el.target.files))
        }
      />
      <DocViewer
        documents={selectedDocs.map((file) => ({
          uri: window.URL.createObjectURL(file),
          fileName: file.name,
        }))}
        pluginRenderers={DocViewerRenderers}
      />
    </>
  );
};
```

**Comment by siduck** [comment]
@cyntler doesnt work :(

![image](https://github.com/cyntler/react-doc-viewer/assets/59060246/b107f3bd-4a7b-4399-b99d-842ae254555e)

**Comment by siduck** [comment]
@cyntler doesnt work with docx files

**Comment by cyntler** [comment]
@siduck Sure! I am really sorry but at this moment it cannot work. File inputs work at the browser level, we have not a public URL to the uploaded file. The library uses Office Viewer from Microsoft using iframe and this supports public files only, served at the some URL.

All you can is upload files to the backend firstly and generate public URLs to the files. Then render <DocViewer /> using generated URLs.

**Comment by siduck** [comment]
> @siduck Sure! I am really sorry but at this moment it cannot work. File inputs work at the browser level, we have not a public URL to the uploaded file. The library uses Office Viewer from Microsoft using iframe and this supports public files only, served at the some URL.
> 
> All you can is upload files to the backend firstly and generate public URLs to the files. Then render using generated URLs.

no worries! btw does it work with blob? 

for example I have this api at my work

```js
/api/customer/milestonedetailsfileupload?type=getfile&blobNam=abc.docx
```

would it be possible to make it work with that?
