### ISSUE TITLE
FilteType prop error on document?

### ISSUE THREAD

**Issue by Wiklem** [cyntler/react-doc-viewer#70]
Hi.

When defining a fileType for document:
` const doc = [
            {
              uri: 'http://....',
              fileType: 'image/png',
              fileName: 'test.png',
            },
          ];`
          
         I get render error:
         `No renderer for file type: image&#x2F;png`

**Comment by cyntler** [comment]
@Wiklem I ping you again. Could you paste your full code here, please? ;)

**Comment by Fxlr8** [comment]
Encountered the same issue. Here is how I got it.
```TSX
    <DocViewer documents={[
        { uri: url }
      ]}
      requestHeaders={{
        'Authorization': 'Bearer ...'
      }}
      prefetchMethod='POST'
    />
```

```
No renderer for file type: image&#x2F;png
```
```
No renderer for file type: application&#x2F;vnd.openxmlformats-officedocument.spreadsheetml.sheet
```

**Comment by cyntler** [comment]
@Wiklem @Fxlr8 Okay but you also need to pass renderers:

```jsx
import DocViewer, { DocViewerRenderers } from "react-doc-viewer";

<DocViewer documents={[
        { uri: url }
      ]}
      pluginRenderers={DocViewerRenderers}
      requestHeaders={{
        'Authorization': 'Bearer ...'
      }}
      prefetchMethod='POST'
    />
```

https://github.com/cyntler/react-doc-viewer#included-renderers
I know, we need to update readme, especially the first `Basic Usage` and include here renderers. I will do it.
