### ISSUE TITLE
Warning: Setting up fake worker.

### ISSUE THREAD

**Issue by Joshuajrodrigues** [cyntler/react-doc-viewer#72]
I get this error in console while I try to open a pdf file, local pdf files also. Warning: Setting up fake worker.

   ```
<DocViewer
                    pluginRenderers={DocViewerRenderers}
 
                    documents={[{ uri: require("C:/Users/username/Documents/app-web/src/components/test.pdf"), fileType: 'application/pdf' }]} />
                    
```
                    

anyone else have this issue ?

**Comment by cyntler** [comment]
@Joshuajrodrigues Thanks for the reporting! Your error looks like its warning, not error. Am I right? Is rendering process working in your case despite the error?

**Comment by Joshuajrodrigues** [comment]
> @Joshuajrodrigues Thanks for the reporting! Your error looks like its warning, not error. Am I right? Is rendering process working in your case despite the error?

@cyntler naa. It doesn't render the pdf file. Odly enough the title of my pdf does get rendered. But the content it self says error. And in console. That warning.


Do note that I use this same configuration to render png and docx files. Which render fine. It's only pdf that gives error. And this was working a few days ago. So I'm not sure what's happening. There is no change in my code base

**Comment by cyntler** [comment]
@Joshuajrodrigues Check the new v1.8.1 release of this library. I changed there the source of PDF worker js file.

**Comment by Joshuajrodrigues** [comment]
@cyntler  Thanks a bunch, this seems to have fixed it !

**Comment by cyntler** [comment]
@Joshuajrodrigues Nice!
