### ISSUE TITLE
Window is not defined NextJS

### ISSUE THREAD

**Issue by Sbphillips19** [cyntler/react-doc-viewer#74]
Having issues with window is not defined.  This is related to the dependency- `react-csv-to-table`, which has an issue open for the same issue.

https://github.com/marudhupandiyang/react-csv-to-table/issues/21

Are you aware of any alternatives to get this package working with NextJS?

**Comment by james-altis** [comment]
Ensure its only imported in the browser where window is available:

```
import dynamic from "next/dynamic"

const DocViewer = dynamic(
  async () => await import("@cyntler/react-doc-viewer"),
  {
    ssr: false,
  }
)

// use DocViewer

```

**Comment by cyntler** [comment]
@Sbphillips19 Yea. It's a problem and we need to resolve this one. I try to do it.
The @james-altis answer seems like quick solution for Next.js.

**Comment by cyntler** [comment]
@Sbphillips19 @james-altis It should be fixed at v.1.10.0.
