### ISSUE TITLE
Error: Blocked script execution in because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

### ISSUE THREAD

**Issue by Osuriel** [cyntler/react-doc-viewer#78]
I've been trying to figure out how to change the iframe to allow javascript to run.
<img width="426" alt="image" src="https://user-images.githubusercontent.com/13215891/200453060-7b295add-a552-40e6-b021-79b4b2af546f.png">

heres the exact error i get: 

index.js:20 Blocked script execution in 'http://localhost:3006/documents/123' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

i found this: https://stackoverflow.com/questions/24531061/blocked-script-execution-in-because-the-documents-frame-is-sandboxed-angular

but idk how i can modify the iframe to make it run javascript.

**Comment by cyntler** [comment]
@Osuriel I don't think it is a problem with this library. Can you paste here more code?

**Comment by SvenDS** [comment]
I have also this problem in React:

`import React, {Component, useEffect, useState, useRef} from 'react';
import DocViewer, { DocViewerRenderers } from "react-doc-viewer";

const test = () => {

  const docs = [
    { uri: require("./test.pdf") } // Local File
  ];


  return (
    <>
      <DocViewer
        documents={docs}
        pluginRenderers={DocViewerRenderers}
      />
    </>
  );
}

export default test`

![Schermafbeelding 2022-11-16 om 08 27 21](https://user-images.githubusercontent.com/32200115/202114531-5f164018-ab5d-4c70-b3e7-0c665ba3d464.png)

**Comment by cyntler** [comment]
@SvenDS I don't know where the problem is. I would need it live, at some public URL, to be able to investigate.

**Comment by mahidaparth7** [comment]
@Osuriel 

Did you find the solution?
I am also facing same issue in local development mode.

**Comment by SirFischer** [comment]
Facing the same issue too, anyone got a solution?

**Comment by hai1337** [comment]
Can replicate issue as well.

**Comment by hamzatekin** [comment]
Same problem here too

**Comment by AkanoCA** [comment]
Same problem

**Comment by ClauPortoMaind** [comment]
I have the same problem in react.  anyone got a solution?

**Comment by tochman** [comment]
Same issue here. Reat App, facing the issue both locally and deployed to Nelify. Both in Chrome and Safari.

**Comment by keckrich** [comment]
I had this issue when displaying a local pdf that I fixed by adding the `require` to the document object:
` { uri: require("./example-files/pdf.pdf") },`

**Comment by mijhaels** [comment]
Same problem in React

**Comment by baotranstudy151293** [comment]
Hi, Please try it. I hope It's helpful
```javascript
import testpdf from "assets/doc/test.pdf"; // In this case my path is "src\assets\doc\test.pdf"
const docs = [{ uri: testpdf }];
```

**Comment by Mathiasfx** [comment]
I have the same issue with a blob file, any suggestion?

**Comment by jacobshirley** [comment]
Same issue here

**Comment by code-xhyun** [comment]
Same problem too.
