### ISSUE TITLE
Cannot find module '@cyntler/react-doc-viewer' or its corresponding type declarations.

### ISSUE THREAD

**Issue by dpcamp** [cyntler/react-doc-viewer#8]
I just installed with `npm i @cyntler/react-doc-viewer`  But I can' seem to import it into my app. 

I've tried `import DocViewer from "react-doc-viewer";` then `import DocViewer from "@cyntler/react-doc-viewer";`

both return the same error

**Comment by dpcamp** [comment]
My bad, didn't realize this was a types issue. Worked around this by adding a declaration.

**Comment by manoj-paramesh-learngram-ai** [comment]
I have the same issue , but not using typescript , How would I get this to work ?
