### ISSUE TITLE
Controls on images

### ISSUE THREAD

**Issue by MathisTimo** [cyntler/react-doc-viewer#80]
Hello, I don't know if it's possible to enable controls (like on the pdf files) for the images, to download, zoom in and out.

If it's possible how can I enable it ? And if not could you implement this feature ? 

Thanks for the help !

**Comment by MathisTimo** [comment]
Update: I created a custom image renderer, with a [React-zoom-pan-pinch](https://prc5.github.io/react-zoom-pan-pinch/?path=/docs/docs-introduction--page) component inside. 

The final result is very similar to the PDFRenderer, and the features are the same 😃

**Comment by Ruslan27032000** [comment]
@MathisTimo Can you share example?

**Comment by emiliobasualdo** [comment]
@MathisTimo would you share the code for that renderer?
Its gonna save many of us something. 😃

**Comment by mahammadmansur95** [comment]
Can you share us the code here. We also need similar features.
