### ISSUE TITLE
Lifting dependency support for react and react-dom to 17.0.2+

### ISSUE THREAD

**Issue by daniellin215** [cyntler/react-doc-viewer#81]
Currently peer dependency only supports up to 16.8.6 for react and react-dom, is there a possibility to bump support for more recent react versions?

**Comment by cyntler** [comment]
@daniellin215 are you sure? Check `package.json` -> `peerDependencies`. https://github.com/cyntler/react-doc-viewer/blob/main/package.json#L71.

**Comment by daniellin215** [comment]
@cyntler maybe this is an issue with my setup? My terminal shows the following after npm install. 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/41842771/202292683-b0f1f14f-bf03-4104-bb67-0ad1667e533f.png">

**Comment by cyntler** [comment]
@daniellin215 Yes, it is probably because react-csv-to-table has a different peer dependency. Is `npm i --legacy-peer-deps` command working?

**Comment by daniellin215** [comment]
Yes that worked, thanks so much

**Comment by cyntler** [comment]
@daniellin215 At the new version v1.10.0, I removed `react-csv-to-table` and provided some another solution for CSV files rendering. So the latest version should be working as a normal, without `--legacy-peer-deps` flag.
