### ISSUE TITLE
Displaying blob dosen't work

### ISSUE THREAD

**Issue by Quocphu123** [cyntler/react-doc-viewer#89]
i have a blob return from API and use it with createObjectURL but it doesn't work 

my blob
![Capture](https://user-images.githubusercontent.com/52072325/204078823-11b3fa99-4bc9-4f71-ac4f-4c8805050b1c.PNG)

where i use
![image](https://user-images.githubusercontent.com/52072325/204078936-76187242-cbd3-45f6-b507-6ae062fc5816.png)

the result 
![image](https://user-images.githubusercontent.com/52072325/204078874-fc827a1b-1e69-4e56-a124-acd34c19ecac.png)

is there any chance to display it? like base64 or something like that

**Comment by cyntler** [comment]
@Quocphu123 This library supports MS docs displaying by `https://view.officeapps.live.com/op/embed.aspx` (https://github.com/cyntler/react-doc-viewer/blob/main/src/plugins/msdoc/index.tsx#L13) at the moment. Unfortunately it doesn't work with blobs or base64 urls. The only one possibility is to use a public url to the file.

**Comment by Donhv** [comment]
so sad.
