### ISSUE TITLE
No renderer for file type: text&#x2F:html

### ISSUE THREAD

**Issue by ConanCodes** [cyntler/react-doc-viewer#95]
Good Morning,

I'm using this in my project and I'm running into an issue with trying to do a basic render of ant.html from "gradle-6.7/docs/userguide/ant.html". I have it set up very basically with it hitting a local host.

```
// ** Imports .... //

import DocViewer, { DocViewerRenderers } from "react-doc-viewer";

function DocumentViewer() {
  const props = useSelector((props: RootState) => props);

  const docs = [{ uri: "https://Localhost:8443/api/v1/.../file", fileType: "text/html" }];
  const header = { "Authorization": "Bearer " + props.ACCESS_TOKEN };

  return (
    <DocViewer
      documents={docs}
      prefetchMethof="GET"
      requestHeaders={header}
    />
  );
}


export default DocumentViewer;
```
But this returns an error to the screen that says `"No renderer for file type: text&#x2F;html"`. When I check the network response I see the file as expected so I know it was received 

After I saw this error I tried using  `pluginRenderer={DocViewerRenderers}`. Using that causes my page to crash with a console error showing ` "Uncaught DOMException: String contains an invalid character"`.

I thought there was an issue with the encode/decode of the html so I tried `decodeURI()` before the URL hit the DocViewer but had no luck. When I added `config={{ noRenderer: { overrideComponent: testError }, }}` to try and look deeper into the issue the DocViewer would return "text/html" as expected.

This is my first time posting an issue on Git, hopefully I was able to explain everything well enough, any help with this issue would be great!

**Comment by cyntler** [comment]
@ConanCodes `prefetchMethof="GET"`? Change to `prefetchMethod` please. Hmm, I don't know where is the problem. Are you sure your request `"https://Localhost:8443/api/v1/.../file"` returns html file? Can you show the screenshot of Web Inspector's Network tab?

**Comment by ConanCodes** [comment]
> @cyntler Thanks for getting back to me! `prefetchMethod` was correct just a typo on here. As for the text/html even when the `fileType` is left out it errors with the same message. 

Here is a link to the html file I'm using a store of.
https://docs.gradle.org/current/userguide/ant.html

After a little more diggig when I donot use `prefetchMethod` I get nothing back, and the get is never called, so I do have to use it. But, it doesn't matter if I include `fileType`

**Comment by cyntler** [comment]
@ConanCodes I don't understand everything. You have a backend which serves the html file (this html file: `https://docs.gradle.org/current/userguide/ant.html`). Am I right?

**Comment by cyntler** [comment]
@ConanCodes If yes, please provide your backend code and this endpoint.

**Comment by ConanCodes** [comment]
@cyntler Hopefully I don't embarrass myself too much but I'm just a jr at this stuff. All I have access too is the UI stuff and the API call to it. If you think this could be an issue on their end I will bug them!

**Comment by ermarkar** [comment]
Hi am facing the same!!

  ```
<DocViewer prefetchMethod="GET" style={{ borderRadius: "10px", height: "100%" }} documents={[doc]}
      pluginRenderers={DocViewerRenderers} />
```
and the object 
```
{
    "id": 14,
    "createdAt": "2024-01-04T12:50:14.649Z",
    "name": "Hello",
    "url": "docs/ENQ_24/xt8rbe8N.html",
    "uri": "http://localhost:8085/api/enquiries/docs/preview?key=docs/ENQ_24/xt8rbe8N.html",
    "fileType": "html"
}
```

if i hit the url directly to postman it returns html file but in network tab for the call of the preview api it is showing 283B downloaded but in preview and response showing nothing to preview and this request has no data available. 

And on ui I am getting
```

Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at http://localhost:3000/static/js/vendors-node_modules_cyntler_react-doc-viewer_dist_esm_index_js.chunk.js:1162:23
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:61777:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:63270:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:63242:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:63232:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:63222:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:65107:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:65059:18)
    at http://localhost:3000/static/js/bundle.js:64874:13
    at workLoop (http://localhost:3000/static/js/bundle.js:81973:38)
```

any solution for this?

i have confirmed from calling api and in postman url serves the html page
